[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gravdyn"
version = "0.1.2"
description = "Python package for computing gravitational fields of irregular celestial bodies using point-mass, polyhedral, and expansion-based methods."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Safwan Aljbaae", email = "safwan.aljbaae@gmail.com"}
]
dependencies = [
    "numpy>=2.0,<3",
    "trimesh>=4.0,<5",
    "matplotlib>=3.8,<4",
    "plotly>=5.18,<7",
    "pandas>=2.2,<4",
    "jax>=0.4,<1",
    "requests>=2.31,<3",
    "sympy>=1.12,<2",
    "networkx>=3.2,<4"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
